### ISSUE TITLE
synapse_janitor.sql to remove rooms with just 1 user after X Days

### ISSUE THREAD

**Issue by sraja415** [xwiki-labs/synapse_scripts#2]
I should be able to remove not just abandoned rooms but also rooms with just 1 user. I want to give 2 months or 60 days for users to be added. If the room has no users or just 1 user for a continuous period of 60 days the remove the room.

**Comment by MurzNN** [comment]
Some users use several rooms with 1 user as notebook, so not good to enable this by default

**Comment by rubo77** [comment]
I would close this issue
